name: Build Docker image

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: matvey-app

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build image
        run: |
          docker build --build-arg GH_PACKAGES_RO_TOKEN="${{ secrets.GH_PACKAGES_RO_TOKEN }}" -t $IMAGE_NAME .
